CMS/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Configuration;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;
using CMS.Models;
using Microsoft.Ajax.Utilities;


namespace CMS.Controllers
{
    public class CourseController : Controller
    {
        private CourseManagementDbContext db = new CourseManagementDbContext();

        // GET: /Course/

        //public ActionResult RegistrarReport()
        //{
            
        //}
        public ActionResult RegistrarReport()
        {
            if (Session["user_email"] == null)
            {
                return RedirectToAction("Login", "UserAccount");
            }
            int userAccountId = (int) Session["user_id"];     //new append
            string html = null;
            //get all semester
            var semesterList = db.Semesters.OrderBy(x => x.Id).ToList();
            foreach (var semester in semesterList)
            {
                //
                var courselistFristSemester = (from c in db.Courses
                    join t in db.Teachers
                        on c.TeacherId equals t.Id into tGroup
                    from t in tGroup.DefaultIfEmpty()
                    join time in db.Times
                        on c.TimeId equals time.Id into timeGroup
                    from time in timeGroup.DefaultIfEmpty()
                    where c.Semester == semester.Name &&
                    c.UserAccountId == userAccountId           // new append
                    orderby c.Code, c.Section
                    select new
                    {
                        c.Code,
                        c.Name,
                        c.Section,
                        ShortName = t == null ? "" : t.ShortName,
                        Description = time == null ? "" : time.Description
                    }).ToList();
                int numberOfCourseInASemester = courselistFristSemester.Count();
                //string html = "<tr> <td rowspan="+nOfCourse+">First Semester</td></tr>";

                var distinctCourse = courselistFristSemester.Select(x => x.Code).Distinct().ToList(); // x.title

                int numberOfDistinctCourseInASemester = distinctCourse.Count();
                string[] distinctCourseCodeList = new string[numberOfDistinctCourseInASemester + 2];
                int[] numberOfSectionInACourse = new int[numberOfDistinctCourseInASemester + 2];
                int[] rowSpanIndicator = new int[numberOfDistinctCourseInASemester + 2];
                int count = 0;
                foreach (var dCourse in distinctCourse)
                {

                    //string dCourse = distinctCourses;
                    var aCourse = courselistFristSemester.Where(x => x.Code == dCourse).ToList();
                    int numberOfSection = aCourse.Count();
                    distinctCourseCodeList[count] = dCourse;
                    numberOfSectionInACourse[count] = numberOfSection;
                    if (count == 0)
                    {
                        rowSpanIndicator[count] = 0;
                    }
                    else
                    {
                        rowSpanIndicator[count] = rowSpanIndicator[count - 1] + numberOfSectionInACourse[count - 1];
                    }

                    count++;
                }
                int index = 0;
                int rowIndex = 0;
                //string html = null;  // shift top of the loop

                foreach (var course in courselistFristSemester)
                {
                    html += "<tr>";
                    if (index == 0)
                    {
                        html += "<td rowspan=\"" + numberOfCourseInASemester + "\">"+semester.Name;  //Term 1
                    }
                    if (rowSpanIndicator[rowIndex] == index)
                    {
                        html += "<td rowspan=\"" + numberOfSectionInACourse[rowIndex] + "\">";
                        html += distinctCourseCodeList[rowIndex];
                        html += "</td>";

                        html += "<td rowspan=\"" + numberOfSectionInACourse[rowIndex] + "\">";
                        //find the courseTitle by courseCode
                        string courseCodeForCourseTitle = distinctCourseCodeList[rowIndex];
                        var courseTitleList =
                            db.Courses.Where(x => x.Code == courseCodeForCourseTitle).ToList();
                        string courseTitle = null;
                        foreach (var course1 in courseTitleList)
                        {
                            courseTitle = course1.Name;
                        }
                        //End of Find the courseTitle by courseCode

                        html += courseTitle; //distinctCourseCodeList[rowIndex]
                        html += "</td>";
                        rowIndex++;
                    }
                    html += "<td>" + course.Section + "</td>";
                    html += "<td>" + course.ShortName + "</td>";
                    html += "<td>" + course.Description + "</td>";

                    html += "</tr>";
                    index++;

                }
            }
            //Response.AppendHeader("Content-Type", "application/msword");
            //Response.AppendHeader("Content-disposition", "attachment; filename=myword.doc");
            //Response.Write(html);
            ViewBag.html = html;
            return View();
        }






        public ActionResult CourseAssignToTeacher()
        {
            if (Session["user_email"] == null)
            {
                return RedirectToAction("Login", "UserAccount");
            }
            int userAccountId = (int) Session["user_id"];     //new append
            ViewBag.TeacherList = db.Teachers.Where(x=>x.UserAccountId == userAccountId).ToList();   //new where append
            var courses = db.Courses.Where(x=>x.UserAccountId==userAccountId).ToList();              //new where append
            var l = new List<string>();
            foreach (var course in courses)
            {
                string code = course.Code;
                l.Add(code);
            }

            ViewBag.CourseList = l.Distinct();
            ViewBag.TimeList = db.Times.ToList();

            return View();
        }

        [HttpPost]
        public ActionResult CourseAssignToTeacher(CourseTeacher courseTeacher)
        {
            if (Session["user_email"] == null)
            {
                return RedirectToAction("Login", "UserAccount");
            }
            int userAccountId = (int)Session["user_id"];     //new append
            ViewBag.TeacherList = db.Teachers.Where(x=>x.UserAccountId==userAccountId).ToList();    //new Where append
            var courses = db.Courses.Where(x=>x.UserAccountId==userAccountId).ToList();            //new where append
            var l = new List<string>();
            foreach (var course in courses)
            {
                string code = course.Code;
                l.Add(code);
            }

            ViewBag.CourseList = l.Distinct();
            ViewBag.TimeList = db.Times.ToList();

            var query = (from c in db.Courses
                where c.Code == courseTeacher.CourseCode &&
                      c.Section == courseTeacher.Section &&
                      c.UserAccountId == userAccountId              //new append
                select c).ToList();
            Course aCourse = new Course();

            foreach (var course in query)
            {
                

                course.TeacherId = courseTeacher.Teacher;
                course.TimeId = courseTeacher.TimeId;
            }

            db.SaveChanges();


            return View();
        }



        public ActionResult Index()
        {
            if (Session["user_email"] == null)
            {
                return RedirectToAction("Login", "UserAccount");
            }
            int userAccountId = (int)Session["user_id"];     //new append
            List<CourseAllInformation> courses = (from c in db.Courses
                              join t in db.Teachers
                                  on c.TeacherId equals t.Id into tGroup
                              from teacherName in tGroup.DefaultIfEmpty()
                              join time in db.Times
                                  on c.TimeId equals time.Id into timeGroup
                              from TimeInfo in timeGroup.DefaultIfEmpty()
                              where c.UserAccountId == userAccountId         //new append
                              orderby c.Code, c.Section
                              select new CourseAllInformation()
                              {
                                  Id = c.Id,
                                  Code = c.Code,
                                  Name = c.Name,
                                  Section =  c.Section,
                                  Semester = c.Semester,
                                  LabRequired = c.LabRequired,
                                  LabCourse = c.IsItaLabCourse,
                                  Faculty = teacherName == null ? String.Empty : teacherName.ShortName,
                                  Time = TimeInfo == null ? String.Empty : TimeInfo.Description
                              }).ToList();

            List<CourseAllInformation> coursesOrderBySemester = new List<CourseAllInformation>();
            var semesters = (from s in db.Semesters
                orderby s.Id
                select s).ToList();
            foreach (var semester in semesters)
            {
                foreach (var aCourse in courses)
                {
                    if (semester.Name == aCourse.Semester)
                    {
                        coursesOrderBySemester.Add(aCourse);

CMS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Course Management System</title>
    <link rel="shortcut icon" type="image/ico" href="~/Images/UniFavicon.png">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        label.error {
            color: tomato;
            font-weight: normal;
        }

        #main {
            width: 100%;
            height: 5%;
            font-family: Fira Sans;
        }
        .navbar-brand{
            font-size: 22px;
            font-style: italic;
            font-weight: bold;
        }
    </style>

</head>
<body>


    <div class="navbar navbar-inverse navbar-fixed-top" id="main">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Course Management System", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse navbar-right">
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li style="margin-top: 0px;"><a href="@Url.Action("Index", "Home")" class="glyphicon glyphicon-home"></a></li>
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Course <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Save Course", "Create", "Course")</li>
                                <li>@Html.ActionLink("Course Assign To Faculty", "CourseAssignToTeacher", "Course")</li>
                                <li>@Html.ActionLink("View Course Statistics", "Index", "Course")</li>
                                <li class="divider"></li>
                                <li>@Html.ActionLink("Unassign All Courses", "Index", "Course")</li>
                            </ul>
                        </li>

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Teacher <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Save Faculty", "Create", "Teacher")</li>
                                <li>@Html.ActionLink("View All Faculty", "Index", "Teacher")</li>
                            </ul>
                        </li>

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Report <b class="caret"></b></a>
                            <ul class="dropdown-menu">

                                <li>@Html.ActionLink("Full-Time Faculty", "FullTimeFacultyCourseLoad", "Teacher")</li>
                                <li>@Html.ActionLink("Part-Time Faculty", "PartTimeFacultyCourseLoad", "Teacher")</li>
                                <li>@Html.ActionLink("Registrar Report", "RegistrarReport", "Course")</li>
                            </ul>
                        </li>


                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer style="font-family: Fira Sans">
            <p>&copy; @DateTime.Now.Year - All Rights Reserved by ULAB</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script>
        $('.dropdown').hover(function () {
            $('.dropdown-toggle', this).trigger('click');
        });
    </script>
    @RenderSection("scripts", required: false)
</body>
</html>




@*<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Course Management System</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        label.error {
            color:tomato;
            font-weight: normal;

        }
    </style>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("CMS", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Save Teacher", "Create", "Teacher")</li>
                    <li>@Html.ActionLink("Save Course", "Create", "Course")</li>
                    <li>@Html.ActionLink("Course Assign", "CourseAssignToTeacher", "Course")</li>
                    <li>@Html.ActionLink("FullTime", "FullTimeFacultyCourseLoad", "Teacher")</li>
                    <li>@Html.ActionLink("PartTime", "PartTimeFacultyCourseLoad", "Teacher")</li>
                    <li>@Html.ActionLink("Report", "RegistrarReport", "Course")</li>
                    
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Course Management System</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>*@