CMS/Models/UserAccount.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Security.Cryptography;
using System.Web;

namespace CMS.Models
{
    public class UserAccount
    {
        
        public int Id { get; set; }
        [EmailAddress]
        public string Email { get; set; }
        
        public string Password { get; set; }
    }
}

CMS/Controllers/UserAccountController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CMS.Models;
using Microsoft.Owin.Security.OAuth.Messages;

namespace CMS.Controllers
{
    public class UserAccountController : Controller
    {
        private CourseManagementDbContext db = new CourseManagementDbContext();


        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(UserAccount user)
        {
            var aUser = db.UserAccounts.Where(x => x.Email == user.Email && x.Password == user.Password);
            foreach (var boss in aUser)
            {
                Session["user_id"] = boss.Id;
                Session["user_email"] = boss.Email;
            }
            if (Session["user_email"] != null)
            {
                return RedirectToAction("Index", "Home");
            }
            ViewBag.message = "Email or Password is incorrect!!!";
            return View(user);    
        }

        public ActionResult Logout()
        {
            Session["user_id"] = null;
            Session["user_email"] = null;            
            return RedirectToAction("Index", "Home");
        }

        //// GET: /UserAccount/Create
        public ActionResult Registrar()
        {
            return View();
        }

        // POST: /UserAccount/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Registrar([Bind(Include = "Id,Email,Password")] UserAccount useraccount)
        {
            if (ModelState.IsValid)
            {
                if (!db.UserAccounts.Any(x => x.Email == useraccount.Email))
                {
                    db.UserAccounts.Add(useraccount);
                    db.SaveChanges();
                    return RedirectToAction("Login");
                }
            }
            ViewBag.message = "This email is already used. Please register with another email.";
            return View(useraccount);
        }



        //// GET: /UserAccount/
        //public ActionResult Index()
        //{
        //    return View(db.UserAccounts.ToList());
        //}

        //// GET: /UserAccount/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    UserAccount useraccount = db.UserAccounts.Find(id);
        //    if (useraccount == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(useraccount);
        //}

        //// GET: /UserAccount/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: /UserAccount/Create
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include="Id,Email,Password")] UserAccount useraccount)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.UserAccounts.Add(useraccount);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    return View(useraccount);
        //}

        //// GET: /UserAccount/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    UserAccount useraccount = db.UserAccounts.Find(id);
        //    if (useraccount == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(useraccount);
        //}

        //// POST: /UserAccount/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include="Id,Email,Password")] UserAccount useraccount)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(useraccount).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    return View(useraccount);
        //}

        //// GET: /UserAccount/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    UserAccount useraccount = db.UserAccounts.Find(id);
        //    if (useraccount == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(useraccount);
        //}

        //// POST: /UserAccount/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    UserAccount useraccount = db.UserAccounts.Find(id);
        //    db.UserAccounts.Remove(useraccount);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CMS/Views/UserAccount/Create.cshtml
@model CMS.Models.UserAccount

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "UserAccount", FormMethod.Post, new {ID="userAccountForm"})) 
{
    @Html.AntiForgeryToken()
    
    
    <div class="form-horizontal">
        <h4>UserAccount</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Password, htmlAttributes:new{@type="password"})
                @Html.ValidationMessageFor(model => model.Password)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


@section Scripts {

    <script src="~/Scripts/jquery-2.2.3.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script>
        $(document).ready(function() {

            $("#UserAccountForm").validate({
                rules: {
                    Email: {
                        required: true,
                        email: true,
                    },
                    Password: {
                        required: true,
                        password: true,
                        minlength: 5
                    },
                },
                messages: {
                    Email: {
                        required: "Please provide an email.",
                        email: "Please provide a valid email.",
                    },
                    Password: {
                        required: "Please provide a Password",
                        minlength: "Password must be atleast 5 characters long",
                    },
                }
            });

            $('#message').delay(5000).fadeOut();


        });
    </script>
}

CMS/Views/UserAccount/Delete.cshtml
@model CMS.Models.UserAccount

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UserAccount</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CMS/Views/UserAccount/Details.cshtml
@model CMS.Models.UserAccount

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>UserAccount</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CMS/Views/UserAccount/Edit.cshtml
@model CMS.Models.UserAccount

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserAccount</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password)
                @Html.ValidationMessageFor(model => model.Password)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CMS/Views/UserAccount/Index.cshtml
@model IEnumerable<CMS.Models.UserAccount>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Password)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Password)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

CMS/Views/UserAccount/Login.cshtml
@model CMS.Models.UserAccount

@{
    ViewBag.Title = "log in";
}

<h2>log in</h2>


@using (Html.BeginForm("Login", "UserAccount", FormMethod.Post, new { ID = "userAccountForm" }))
{
    @Html.AntiForgeryToken()


    <div class="form-horizontal">
        <h4>UserAccount</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Email, htmlAttributes: new { @class = "form-control" })
               
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Password, htmlAttributes: new { @type = "password", @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Log in" class="btn btn-default" />
            </div>
        </div>
    </div>
    <div id="message" style="color: red">@ViewBag.message</div>
}



@section Scripts {

    <script src="~/Scripts/jquery-2.2.3.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script>
        $(document).ready(function () {

            $("#userAccountForm").validate({
                rules: {
                    Email: {
                        required: true,
                        email: true,
                    },
                    Password: {
                        required: true,
                        
                    },
                },
                messages: {
                    Email: {
                        required: "Please provide an email.",
                        email: "Please provide a valid email.",
                    },
                    Password: {
                        required: "Please provide a Password",
                        
                    },
                }
            });

            $('#message').delay(5000).fadeOut();


        });
    </script>
}

CMS/Views/UserAccount/Registrar.cshtml
@model CMS.Models.UserAccount

@{
    ViewBag.Title = "Register";
}

<h2>Registation Page</h2>


@using (Html.BeginForm("Registrar", "UserAccount", FormMethod.Post, new { ID = "userAccountForm" }))
{
    @Html.AntiForgeryToken()


    <div class="form-horizontal">
        <h5>Please register to use CMS services</h5>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Email, htmlAttributes: new { @class = "form-control" })

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Password, htmlAttributes: new { @type = "password", @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Log in" class="btn btn-default" />
            </div>
        </div>
    </div>
    <div id="message" style="color: red; font-weight: bold; margin-left: 100px;">@ViewBag.message</div>
}



@section Scripts {

    <script src="~/Scripts/jquery-2.2.3.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script>
        $(document).ready(function () {

            $("#userAccountForm").validate({
                rules: {
                    Email: {
                        required: true,
                        email: true,
                    },
                    Password: {
                        required: true,
                        minlength: 3,

                    },
                },
                messages: {
                    Email: {
                        required: "Please provide an email.",
                        email: "Please provide a valid email.",
                    },
                    Password: {
                        required: "Please provide a Password",

                    },
                }
            });

            $('#message').delay(8000).fadeOut();


        });
    </script>
}