CMS/Models/Teacher.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CMS.Models
{
    public class Teacher
    {
        public int Id { get; set; }
        public string Name { get; set; }
        [DisplayName("Short Name")]
        
        public string ShortName { get; set; }
        public string Email { set; get; }
        [DisplayName("Contact No.")]
        public string ContactNo { get; set; }
        public string Designation { get; set; }
        public string Status { get; set; }

        [DisplayName("Number of Course")]
        public int NumberOfCourse { get; set; }
        [NotMapped]
        public int RemainingCourse { get; set; }
        public int UserAccountId { get; set; }
    }
}

CMS/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Security.Cryptography;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using CMS.Models;
using iTextSharp.text;
using iTextSharp.text.pdf;
using Microsoft.Ajax.Utilities;
using OfficeOpenXml;
using System.IO;
using System.Net.Mail;
using System.Net.Mime;
using System.Net.Mail;

namespace CMS.Controllers
{
    public class TeacherController : Controller
    {
        private CourseManagementDbContext db = new CourseManagementDbContext();

        // GET: /Teacher/

        public ActionResult FullTimeFacultyCourseLoad()
        {
            if (Session["user_email"] == null)
            {
                return RedirectToAction("Login", "UserAccount");
            }

            int userAccountId = (int) Session["user_id"];     //new append
            var teacherStatistics = (from t in db.Teachers
                join c in db.Courses
                    on t.Id equals c.TeacherId into cGroup
                    where t.Status == "Full Time" &&
                    t.UserAccountId == userAccountId        //new append
                orderby t.Designation descending  
                select new
                {
                    TeacherInfo = t,
                    CourseInfo = from cg in cGroup
                                 where cg.UserAccountId == userAccountId      //new append
                                 orderby cg.Code ascending 
                                 select cg
                }).ToList();
            
            List<TeacherStatistics> teacherStatisticses = new List<TeacherStatistics>();
            int count=0;
            foreach (var teacherStatistic in teacherStatistics)
            {
                TeacherStatistics aTeacherStatistics = new TeacherStatistics();
                aTeacherStatistics.Name = teacherStatistic.TeacherInfo.Name;
                aTeacherStatistics.Designation = teacherStatistic.TeacherInfo.Designation;
                aTeacherStatistics.NumberOfCourse = teacherStatistic.TeacherInfo.NumberOfCourse;
                count = 0;
                foreach (var courseInfo in teacherStatistic.CourseInfo)
                {
                    if (count != 0)
                    {
                        aTeacherStatistics.Courses += ", ";
                    }

                    aTeacherStatistics.Courses += courseInfo.Code;
                    aTeacherStatistics.Courses += "(";
                    aTeacherStatistics.Courses += courseInfo.Section;
                    aTeacherStatistics.Courses += ")";
                    count++;
                } 

                teacherStatisticses.Add(aTeacherStatistics);
            }


            List<TeacherStatistics> teacherStatisticsesWithDesignationOrder = new List<TeacherStatistics>();
            List<Designation> designations = db.Designations.OrderBy(x => x.Id).ToList();
            foreach (Designation designation in designations)
            {
                foreach (var aTeacher in teacherStatisticses)
                {
                    if (designation.Name == aTeacher.Designation)
                    {
                        teacherStatisticsesWithDesignationOrder.Add(aTeacher);
                    }
                }
            }

            return View(teacherStatisticsesWithDesignationOrder);
        }

        public ActionResult FullTimeFacultyCourseLoadReport()
        {
            var document = new Document(PageSize.A3, 100, 100, 50, 50);
            var output = new MemoryStream();
            var writer = PdfWriter.GetInstance(document, output);
            document.Open();


            var titleFont = FontFactory.GetFont("Arial", 18, Font.BOLD);
            var subTitleFont = FontFactory.GetFont("Arial", 14, Font.BOLD);
            var boldTableFont = FontFactory.GetFont("Arial", 12, Font.BOLD);
            var endingMessageFont = FontFactory.GetFont("Arial", 10, Font.ITALIC);
            var bodyFont = FontFactory.GetFont("Arial", 12, Font.NORMAL);

            document.Add(new Paragraph("Full Time Faculty Course Load ", titleFont));
            document.Add(new Paragraph("Fall 2016 ", subTitleFont));
            document.Add(new Paragraph("Department of Computer Science and Engineering ", subTitleFont));

            document.Add(Chunk.NEWLINE);


            var teacherTable = new PdfPTable(4);
            teacherTable.WidthPercentage = 100F; 
            teacherTable.SpacingBefore = 0;
            teacherTable.SpacingAfter = 0;

            int[] widths = new int[] { 8, 7, 5, 16 };
            teacherTable.SetWidths(widths);

            teacherTable.AddCell(new Phrase("Name", boldTableFont));
            teacherTable.AddCell(new Phrase("Designation", boldTableFont));
            teacherTable.AddCell(new Phrase("No of Course", boldTableFont));
            teacherTable.AddCell(new Phrase("Courses", boldTableFont));

            var teacherStatistics = (from t in db.Teachers
                                     join c in db.Courses
                                         on t.Id equals c.TeacherId into cGroup
                                     where t.Status == "Full Time"
                                     orderby t.Designation descending
                                     select new
                                     {
                                         TeacherInfo = t,
                                         CourseInfo = from cg in cGroup
                                                      orderby cg.Code ascending
                                                      select cg
                                     }).ToList();

            List<TeacherStatistics> teacherStatisticses = new List<TeacherStatistics>();
            int count = 0;
            foreach (var teacherStatistic in teacherStatistics)
            {
                TeacherStatistics aTeacherStatistics = new TeacherStatistics();
                aTeacherStatistics.Name = teacherStatistic.TeacherInfo.Name;
                aTeacherStatistics.Designation = teacherStatistic.TeacherInfo.Designation;
                aTeacherStatistics.NumberOfCourse = teacherStatistic.TeacherInfo.NumberOfCourse;
                count = 0;
                foreach (var courseInfo in teacherStatistic.CourseInfo)
                {
                    if (count != 0)
                    {
                        aTeacherStatistics.Courses += ", ";
                    }

                    aTeacherStatistics.Courses += courseInfo.Code;
                    aTeacherStatistics.Courses += "(";
                    aTeacherStatistics.Courses += courseInfo.Section;
                    aTeacherStatistics.Courses += ")";
                    count++;
                }
                teacherTable.AddCell(aTeacherStatistics.Name);
                teacherTable.AddCell(aTeacherStatistics.Designation);
                teacherTable.AddCell(aTeacherStatistics.NumberOfCourse.ToString());
                teacherTable.AddCell(aTeacherStatistics.Courses);


                teacherStatisticses.Add(aTeacherStatistics);
            }
            document.Add(teacherTable);
            document.Close();
            Response.ContentType = "application/pdf";
            Response.AddHeader("content-disposition", "attachment;  filename=FullTimeFaculty.pdf");
            Response.BinaryWrite(output.ToArray());
            return View(teacherStatisticses);
        }
  

        public ActionResult FullTimeFacultyCourseLoadReportExcel()
        {

            var teacherStatistics = (from t in db.Teachers
                                     join c in db.Courses
                                         on t.Id equals c.TeacherId into cGroup
                                     where t.Status == "Full Time"
                                     orderby t.Designation descending
                                     select new
                                     {
                                         TeacherInfo = t,
                                         CourseInfo = from cg in cGroup
                                                      orderby cg.Code ascending
                                                      select cg
                                     }).ToList();


            List<TeacherStatistics> teacherStatisticses = new List<TeacherStatistics>();
            int count = 0;
            foreach (var teacherStatistic in teacherStatistics)
            {
                TeacherStatistics aTeacherStatistics = new TeacherStatistics();
                aTeacherStatistics.Name = teacherStatistic.TeacherInfo.Name;
                aTeacherStatistics.Designation = teacherStatistic.TeacherInfo.Designation;
                aTeacherStatistics.NumberOfCourse = teacherStatistic.TeacherInfo.NumberOfCourse;
                count = 0;
                foreach (var courseInfo in teacherStatistic.CourseInfo)
                {
                    if (count != 0)
                    {
                        aTeacherStatistics.Courses += ", ";
                    }

                    aTeacherStatistics.Courses += courseInfo.Code;
                    aTeacherStatistics.Courses += "(";
                    aTeacherStatistics.Courses += courseInfo.Section;
                    aTeacherStatistics.Courses += ")";
                    count++;
                }
                teacherStatisticses.Add(aTeacherStatistics);
            }

            ExcelPackage excel = new ExcelPackage();
            var workSheet = excel.Workbook.Worksheets.Add("Sheet1");
            workSheet.Cells[1, 1].LoadFromCollection(teacherStatisticses, true);
            using (var memoryStream = new MemoryStream())
            {
                Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                Response.AddHeader("content-disposition", "attachment;  filename=FullTime.xlsx");

CMS/Views/Teacher/Create.cshtml
@using System.Data.Entity.ModelConfiguration.Conventions
@model CMS.Models.Teacher

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Teacher", FormMethod.Post, new {ID="TeacherSaveForm"} )) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Teacher</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Name, htmlAttributes:new{@class="form-control"})
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShortName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ShortName, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ShortName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Email, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactNo, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ContactNo, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ContactNo)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Designation, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Designation, new SelectList(ViewBag.DesignationList, "Name", "Name"), htmlAttributes:new{@class="form-control"})
                @Html.ValidationMessageFor(model => model.Designation)
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.Status, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Status, new SelectList(ViewBag.StatusList, "Name", "Name"), htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Designation)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumberOfCourse, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.NumberOfCourse, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.NumberOfCourse)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
        
        <div style="color: green; font-weight: bold" class="col-md-offset-2 col-md-10" id="message">
            @ViewBag.message
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    
    <script src="~/Scripts/jquery-2.2.3.js"></script>
    
    <script src="~/Scripts/jquery.validate.js"></script>
    <script>
        $(document).ready(function() {


            $("#TeacherSaveForm").validate({
                rules: {
                    Name: "required",
                    ShortName: {
                        required: true,
                        remote: {
                            url: '@Url.Action("IsShortNameExist", "Teacher")',
                            type: "post",
                           
                        }
                    },

                    Email: {
                        required: true,
                        email: true,
                        remote: {
                            url: '@Url.Action("IsEmailExist", "Teacher")',
                            type: "post",
                        }
                    },
                    ContactNo: {
                        required: true
                    },
                    Designation: {
                        required: true
                    },


                    NumberOfCourse: {
                        min: 0,
                        max: function() {
                            if ($("#Status").val() == "Part Time")
                                return 2;
                            else {
                                return 5;
                            }
                        },
                        required: true,
                    },


                },
                messages: {
                    Name: "Please provide Teacher's name.",
                    Email: {
                        required: "Please provide an email.",
                        email: "Please provide a valid email.",
                        remote: "Short Name is already taken"
                    },
                    shortName: {
                        required: "Please provide your password.",
                    },
                    NumberOfCourse: {
                        required: "Please Give input"
                    },

                }
            });

            $('#message').delay(5000).fadeOut();


        });
    </script>
}

CMS/Views/Teacher/Delete.cshtml
@model CMS.Models.Teacher

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Teacher</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShortName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShortName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Designation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Designation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumberOfCourse)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumberOfCourse)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CMS/Views/Teacher/Details.cshtml
@using CMS.Models
@model CMS.Models.TeacherCourseAllInfoViewModel

@{
    ViewBag.Title = "Details";
    int count = 1;
    List<TeachersCourseListViewModel> courseList = Model.CourseList;
}

<h2>Details</h2>

<div>
    <h4>Teacher</h4>
    <hr />
    <div class="form-group">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Teacher.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Teacher.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Teacher.ShortName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Teacher.ShortName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Teacher.Email)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Teacher.Email, new {@class = "form-control" })
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Teacher.ContactNo)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Teacher.ContactNo)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Teacher.Designation)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Teacher.Designation)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Teacher.NumberOfCourse)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Teacher.NumberOfCourse)
            </dd>

        </dl>    
    </div>
    
</div>


<div class="form-group">
    <div >
        <table class="table" id="courseInformation">
            <tr>
                <th>
                    @Html.DisplayName("SerialNo")
                </th>
                <th>
                    @Html.DisplayName("Course Code")
                </th>
                <th>
                    @Html.DisplayName("Course Name")
                </th>
                <th>
                    @Html.DisplayName("Section")
                </th>
                <th>
                    @Html.DisplayName("Time")
                </th>
            </tr>
                        
            @foreach (var course in courseList)
            {
                <tr>
                    <th>
                        @count
                    </th>
                    <th>
                        @course.CourseCode
                    </th>
                    <th>
                        @course.CourseName
                    </th>
                    <th>
                        @course.Section
                    </th>
                    <th>
                        @course.Time 
                    </th>
                </tr>   
                
                count++;
            }
        </table>
    </div>
</div>


<div>
    @Html.ActionLink("Email Course Details to this Faculty", "TeacherDetailsPDF", new { id = Model.Teacher.Id })
</div>


<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Teacher.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CMS/Views/Teacher/Edit.cshtml
@model CMS.Models.Teacher

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Teacher</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Name, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShortName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ShortName, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ShortName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Email, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactNo, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ContactNo, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ContactNo)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Designation, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Designation, new SelectList(ViewBag.DesignationList, "Name", "Name"), htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Designation)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Status, new SelectList(ViewBag.StatusList, "Name", "Name"), htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Designation)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumberOfCourse, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.NumberOfCourse, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.NumberOfCourse)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
 

CMS/Views/Teacher/FullTimeFacultyCourseLoad.cshtml
@model IEnumerable<CMS.Models.TeacherStatistics>
@{
    ViewBag.Title = "FullTimeFacultyCourseLoad";
}
<div id="FullTime">
    <h2 style="font-size: 16px;">Course Load of Full-Time Faculty</h2>

    <table class="table form-group" id="fullTimeFaculty">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Designation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumberOfCourse)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Courses)
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Designation)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NumberOfCourse)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Courses)
                </td>

            </tr>
        }

    </table>
</div>

<div>
    @Html.ActionLink("Download PDF", "FullTimeFacultyCourseLoadReport")
</div>

<div>
    @Html.ActionLink("Download Excel", "FullTimeFacultyCourseLoadReportExcel")
</div>






@*<a href="javascript:genPDF()">Download pdf</a>
<button onclick="printContent('customers')">Print Content</button>

<input type="button" id="excel" name="excel" value="Save as excel" class="form-control"/>
@section Scripts {

    <script type="text/javascript" src="~/Scripts/jquery-2.2.3.js"></script>
    <script type="text/javascript" src="~/Scripts/tableExport.jquery.plugin-master/tableExport.js"></script>
    <script type="text/javascript" src="~/Scripts/tableExport.jquery.plugin-master/jquery.base64.js"></script>
    <script type="text/javascript" src="~/Scripts/tableExport.jquery.plugin-master/jspdf/libs/sprintf.js" ></script>
    <script src="~/Scripts/tableExport.jquery.plugin-master/jspdf/jspdf.js"></script>
    <script type="text/javascript" src="~/Scripts/tableExport.jquery.plugin-master/jspdf/libs/base64.js"></script>

    <script>
        $(document).ready(function() {
            $("#excel").click(function(e) {
                $('#registerReport').tableExport({
                    type: 'pdf',
                    escape: 'false',

                });
            });

        });

    </script>
}*@


@*<div>
    @Html.ActionLink("Send PDF via Email", "SendEmailPDF")
</div>*@

@*<div>
    <a href="#" onclick="return xepOnline.Formatter.Format('FullTime',{render:'download'});">
        Save as PDF (With Script)
    </a>

    @section Scripts {

        <script type="text/javascript" src="~/Scripts/jquery-2.2.3.js"></script>
        <script src="~/Scripts/xepOnline.jqPlugin.js"></script>

    }
</div>*@

CMS/Views/Teacher/FullTimeFacultyCourseLoadReport.cshtml
@model IEnumerable<CMS.Models.TeacherStatistics>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>FullTimeFacultyCourseLoadReport</title>


</head>
<body>
    <h2>Full Time Faculty Course Load</h2>
    <div>


        <table class="table form-group">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Designation)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NumberOfCourse)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Courses)
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Designation)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NumberOfCourse)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Courses)
                    </td>

                </tr>
            }

        </table>
    </div>
</body>
</html>

CMS/Views/Teacher/FullTimeFacultyCourseLoadReportExcel.cshtml
@model IEnumerable<CMS.Models.TeacherStatistics>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>FullTimeFacultyCourseLoadReportExcel</title>


</head>
<body>
    <h2>Full Time Faculty Course Load</h2>
    <div>


        <table class="table form-group">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Designation)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NumberOfCourse)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Courses)
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Designation)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NumberOfCourse)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Courses)
                    </td>

                </tr>
            }

        </table>
    </div>
</body>
</html>